export interface IKeyboardFixedKeyDTO {
  touchKeyboardId: number
  keyPos: number
  caption: string
  backColor: number
  foreColor: number
  fontSize: number
  fontBold: boolean
  linkType: number
  linkId: number
  postEvent: number
  postLayout: number
  settings: string
  value: number
  shortcut: number
  postLinks: string
  journalEntry: string
  programFile: string
  arguments: string
  rowsSpanned: number
  columnsSpanned: number
  cashDrawer: number
  imageName: string
  gradientFill: boolean
  merchantFees: number
  fixedAccount: number
  eftMinAmount: number
  overTender: boolean
  reorderCategories: string
  hideCaption: boolean
  hideCaptionText: string
  reasonGroupName: string
  discount: number
  languages: Uint8Array
  buttonPassword: number
  ttClearItemsSecurityGroup: string
  extras: string
}
